name: ruby_template

run-name: ${{ github.actor }} is learning GitHub Actions

on:
 workflow_dispatch:
 push:
   branches:
     - master
 pull_request:
   types: [opened, synchronize, reopened]
      - name: Print the input name to STDOUT
