name: ruby_template
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
  jobs:
    print-username:
      runs-on: ubuntu-latest
      steps:
        - name: Print the input name to STDOUT
          run: echo The username is ${{ inputs.username }}`:wq
`
